pipeline:
  build:
    image: node:10.2.1
    when:
      branch: master
      event: push
    commands:
      - npm install
      - npm run build
    volumes:
      - /tmp/nodejs/:/root/

  stage-deploy-via-push:
    image: canaldapeca/drone-builder
    when:
      branch: master
      event: push
    environment:
      - AWS_DEFAULT_REGION=us-east-1
    commands:
      - npm publish
      - npm run deploy-storybook
