pipeline:
  build:
    image: node:10.2.1
    when:
      branch: master
      event: push
    commands:
      - npm install
      - npm run build
      - npm publish
      - npm run build-storybook
    volumes:
      - /tmp/nodejs/:/root/
